"""
Documentation Consistency & MECE Coverage Test
Checks for presence of mandatory documents and required sections.
"""
import os
import re
import pytest
from pathlib import Path

class TestDocConsistency:
    """Validate documentation structure and presence."""

    @pytest.fixture
    def doc_root(self):
        """Root directory of the project."""
        return Path(__file__).parent.parent.parent.parent

    def test_mandatory_docs_presence(self, doc_root):
        """Ensure all constitutional and core documents exist."""
        mandatory_root = [
            "README.md",
            "CLAUDE.md",
            "GEMINI.md",
            "PROTOCOL.md",
            "CONVENTION.md"
        ]
        mandatory_docs_v2 = [
            "00-MANIFEST.md",
            "10-invariants.md",
        ]
        for filename in mandatory_root:
            assert (doc_root / filename).exists(), f"Mandatory root doc missing: {filename}"
        # docs-v2 is now the SSOT; _sys/SYSTEM_ARCHITECTURE.md was archived to docs-v2/20-architecture.md
        for filename in mandatory_docs_v2:
            assert (doc_root / "_sys" / "docs-v2" / filename).exists(), f"Mandatory docs-v2 doc missing: {filename}"

    def test_claude_md_sections(self, doc_root):
        """Ensure project CLAUDE.md acts as a pointer to SSOT."""
        claude_md = doc_root / "CLAUDE.md"
        if not claude_md.exists():
            pytest.skip("CLAUDE.md not found in root")
            
        content = claude_md.read_text(encoding="utf-8")
        assert "This file is a **pointer only**" in content, "CLAUDE.md must be a pointer"
        assert "_sys/docs-v2/MOC.md" in content, "CLAUDE.md must link to MOC.md"

    def test_gemini_md_version_sync(self, doc_root):
        """Ensure GEMINI.md acts as a pointer to SSOT."""
        gemini_md = doc_root / "GEMINI.md"
        if not gemini_md.exists():
            pytest.skip("GEMINI.md not found")
            
        content = gemini_md.read_text(encoding="utf-8")
        assert "This file is a **pointer only**" in content, "GEMINI.md must be a pointer"
        assert "_sys/docs-v2/MOC.md" in content, "GEMINI.md must link to MOC.md"

    def test_no_korean_in_sys_scripts(self, doc_root):
        """Ensure no Korean characters in _sys batch scripts (except allowed ones)."""
        sys_dir = doc_root / "_sys"
        allowed_exceptions = ["local.config.bat.template"] # Template might have comments
        
        for root, dirs, files in os.walk(sys_dir):
            for file in files:
                if file.endswith(".bat") and file not in allowed_exceptions:
                    file_path = Path(root) / file
                    # Skip venv activate.bat as it is generated by python
                    if "venv" in str(file_path):
                        continue
                    
                    content = file_path.read_text(encoding="utf-8", errors="ignore")
                    has_korean = re.search(r'[가-힣]', content)
                    assert not has_korean, f"Korean characters found in system script: {file_path}"

    def test_mece_file_structure(self, doc_root):
        """Verify MECE folder structure (no mixed-case system folders)."""
        sys_dir = doc_root / "_sys"
        for item in sys_dir.iterdir():
            if item.is_dir():
                # Conventions say lowercase kebab-case for sys folders
                assert item.name == item.name.lower(), f"System folder name must be lowercase: {item.name}"
